### ISSUE TITLE
Ubuntu under WSL: Browser closed unexpectedly

### ISSUE THREAD

**Issue by Noiade** [evmer/perlego-downloader#15] opened 2022-09-23 21:04 UTC
Traceback (most recent call last):
  File "downloader.py", line 243, in <module>
    asyncio.run(html2pdf())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "downloader.py", line 164, in html2pdf
    browser = await launch(options={
  File "/home/forsite/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/forsite/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/forsite/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by evmer** [comment] 2022-09-24 08:39
duplicate of #9

**Closed by evmer** 2022-09-24 08:39 UTC
Labels: duplicate
