### ISSUE TITLE
what to do?

### ISSUE THREAD

**Issue by rahulbanwasi** [evmer/perlego-downloader#37] opened 2022-11-28 15:33 UTC
OSError: [WinError 14001] The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail

**Comment by rahulbanwasi** [comment] 2022-11-29 10:28
in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by evmer** [comment] 2022-12-01 14:45
Duplicate of #9

**Closed by evmer** 2022-12-01 14:45 UTC
Labels: duplicate
