### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by Faisalnd** [evmer/perlego-downloader#32] opened 2022-11-21 17:34 UTC
Greetings,

I've Mac OS 16, and I followed the instractions exactly step by step by the thing is everytime I run the command it says 
perlego % python3 downloader.py           
download error: Connection timed out

please your support

**Comment by wfan11111** [comment] 2022-11-21 20:55
I have the same issue

**Comment by sfoot13** [comment] 2022-11-21 22:27
> Greetings,
> 
> I've Mac OS 16, and I followed the instractions exactly step by step by the thing is everytime I run the command it says perlego % python3 downloader.py download error: Connection timed out
> 
> please your support

You need an active account, maybe you have problems with the CC or don't have an active subscription.

**Comment by evmer** [comment] 2022-11-21 22:31
Duplicate of #29.
Please follow the troubleshooting process explained there. 

As @sfoot13 said, most likely you mistyped the Auth token/or don't have an active subscription.

**Comment by wfan11111** [comment] 2022-11-22 07:57
I have an active subscription and double-checked the auth token. I also followed #29 and continue to get a connection timed out error.

**Comment by gnawretep** [comment] 2022-11-24 07:02
Is anyone solving this issue? It seems #29 didn't answer it.

**Closed** 2022-11-25 18:05 UTC
Labels: duplicate
