### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by aimiiu** [evmer/perlego-downloader#21] opened 2022-10-04 11:50 UTC
C:\Users\Ioana>python3 C:\Users\Ioana\Desktop\perlego\downloader.py
Traceback (most recent call last):
  File "C:\Users\Ioana\Desktop\perlego\downloader.py", line 2, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by evmer** [comment] 2022-10-04 11:51
duplicate of #17

**Closed by evmer** 2022-10-04 11:51 UTC
